### ISSUE TITLE
[DaMa] Fontbakery checks: Other checks

### ISSUE THREAD

**Issue by pablogamezDaMa** [balsamiq/balsamiqsans#16]
ℹ️ This issue is related to [Dalton Maag's fork of Balsamiq](https://github.com/daltonmaag/balsamiqsans-gft).

Here is a list of warnings that Fontbakery flags and we don't quite understand or see no problem with it:

- [ ] **Glyphs are similar to Google Fonts version?**.
- [ ] **Is there kerning info for non-ligated sequences?** Some combinations (fi, fl, il, ... ) are flagged.

**Comment by madig** [comment]
@m4rc1e Can you please weight in here?

**Comment by m4rc1e** [comment]
>  Glyphs are similar to Google Fonts version?.

Possibly because you've fixed some glyphs. Happy to ignore this.

> Is there kerning info for non-ligated sequences? Some combinations (fi, fl, il, ... ) are flagged.

If your font has ligatures such as fi, fl etc, we expect kerning pairs for these individual letter pairs as well. We do this so apps which don't support the liga feature have a similar appearance. @felipesanches, is this statement correct? also, which apps do not support this feature? test feels redundant to me in 2023.

**Comment by felipesanches** [comment]
This check ("Is there kerning info for non-ligated sequences?") was proposed by @davelab6 in 2016 at https://github.com/googlefonts/fontbakery/issues/1145

**Comment by felipesanches** [comment]
> is this statement correct?

yes

> also, which apps do not support this feature?

I don't know
