### ISSUE TITLE
Glyphs for IPA Extensions are wrong

### ISSUE THREAD

**Issue by dscorbett** [balsamiq/balsamiqsans#6]
All the glyphs for letters in the IPA Extensions block are wrong: the 'cmap' table is mapping them all to their uppercase counterparts.

**Comment by MartinZaske** [comment]
Are you saying the lowercase glyphs were already drawn, and they are just located in the wrong places?

I came here, wanting to extend the typeface by these glyphs:  ɛ ɩ ɔ ʊ   which are the missing lowercase for the already existing Ɛ Ɩ Ɔ and Ʊ. We need the missing glpyhs for our Anii language.

I am willing to draw the missing glyphs. Unless it is just a matter of re-arranging some positions. Would you recommend to open a new issue? 

I am challenged by the source files in .glyph file format. I am on Windows and would use FontForge. Please give me ideas how I can contribute. Anybody willing to convert to something like UFO so that I can edit in FontForge? It would be sad for us, just to make a hack in-house and not share will other users. Thank you.

**Comment by dscorbett** [comment]
The lowercase glyphs have not yet been drawn. I meant that the 'cmap' table maps, for example, both U+0181 LATIN CAPITAL LETTER B WITH HOOK and U+0253 LATIN SMALL LETTER B WITH HOOK to the same glyph: `uni0181`.

One way to contribute would be to draw the glyphs in FontForge, generate a font, and attach it to this issue. A maintainer of Balsamiq could then copy the glyphs into the .glyphs source. I’d wait for a maintainer to confirm this makes sense, though, before doing any work.

**Comment by MartinZaske** [comment]
Thank you, I will draw like you propose and submit for consideration. I want to show that we are willing to help.

**Comment by jibbajabba** [comment]
Issue fixed and delivered.
